# Basic `numpy`

In this notebook we will learn about the python package `numpy`.

By the end of this notebook you will know about:
- Checking the version of a python package,
- `numpy` `ndarray`s,
- `ndarray` functions,
- `numpy` functions,
- Pseudorandom numbers in `numpy` and
- Linear algebra in `numpy`.

## `numpy`

`numpy` is a python package that is a real workhorse of machine learning and data science.

If you are new to python, this will be the first true package you will import. That being said we should check that you have the package installed, try to run the following code chunk. (Note if you installed the Anaconda platform, <a href="https://www.anaconda.com/">https://www.anaconda.com/</a>, `numpy` should be installed already).

In [1]:
## it is standard to import numpy as np
import numpy as np

In [3]:
## let's check what version of numpy you have
## when I wrote this I had version 1.24.2
## yours may be different
print(np.__version__)

2.2.6


If you had a version of `numpy` installed, both of those code chunks should have run without error. If not, you will need to install it onto your machine because we will be using it heavily in the boot camp. For installation instructions check out the `numpy` documentation here, <a href="https://numpy.org/install/">https://numpy.org/install/</a>. If you are unsure how to install a python package in general check our python package installation guide, <a href="https://www.erdosinstitute.org/data-science">https://www.erdosinstitute.org/data-science</a>.


##### Be sure you can run both of the above code chunks before continuing with this notebook, again it should be fine if your package version is slightly different than mine.

### `numpy`'s `ndarray`

While base python likes to store data in objects like `list`s and `tuple`s, in `numpy` data is stored in an `ndarray` it is similar to a list, but has a number of features that make it more useful for numeric data manipulation in a number of data science applications.

<a href="https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html">https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html</a>.

In [5]:
## You can make an array with np.array
## You just put np.array() around a python list or tuple
array1 = np.array([1,2,3,4])
print(array1)
print()
print(type(array1))

[1 2 3 4]

<class 'numpy.ndarray'>


`numpy` `ndarray`s can have any finite number of dimensions. This can be constructed by wrapping `np.array` around a `list` of `list`s.

In [8]:
## this produces a 2-dimensional array
## it is a 2x2 array
array2 = np.array([[1,2,3],[3,4,5]])
print(array2)
print()

## we can check the array's dimensions with np.shape()
## np.shape() returns a tuple with the size of each dimension
## array2 should be a 2 by 2 array
print("array2 is a", np.shape(array2), "ndarray")

[[1 2 3]
 [3 4 5]]

array2 is a (2, 3) ndarray


In [9]:
array2.shape

(2, 3)

<i>Note: the dimensionality of an `ndarray` will be quite important in our boot camp because certain algorithms will not run if the `ndarray` is the wrong shape.</i>

In [14]:
## You code
## Try making a 2x2x2 array
array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(array3)
print()
print(array3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(2, 2, 2)


In [16]:
## You code 
## Try making a 2x2x2x2 array
# array4 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]],[[13,14],[15,16]]])
array4 = np.array([[[[1,1], [2,2]], [[3,3], [4,4]]], [[[1,1], [2,2]], [[3,3], [4,4]]]])
print(array4)
print()
print(np.shape(array4))


[[[[1 1]
   [2 2]]

  [[3 3]
   [4 4]]]


 [[[1 1]
   [2 2]]

  [[3 3]
   [4 4]]]]

(2, 2, 2, 2)


### `ndarray` Functions

#### Vectorized Operations

`ndarray`s are nice because, for the most part, they work the way you'd expect a vector or matrix to work. Let's compare and contrast with python's `list`s.

In [17]:
## You code
## see what happens when you code up 2*list1
list1 = [1,2,3,4]
2*list1

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
## You code
## Now compare it to 2*array1
print(array1)
print(2*array1)


[1 2 3 4]
[2 4 6 8]


In [21]:
## what happens here?
list2 = [5,6,7,8]
list1 + list2

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
## You code
## code up the comparable ndarray expression
## and see what happens
array2 = [5,6,7,8]
print(array2)
print(array1 + array2)

[5, 6, 7, 8]
[ 6  8 10 12]


In [24]:
## Finally what happens here?
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [25]:
## Try the comparable ndarray expression
array1 + 2


array([3, 4, 5, 6])

In [28]:
A = np.array([[1,2], [1,2]])

B = np.array([[1,1], [1,1]])


A*B
print(A," * ",B," = \n",A*B)

[[1 2]
 [1 2]]  *  [[1 1]
 [1 1]]  = 
 [[1 2]
 [1 2]]


### Preset `numpy` Arrays

There are a number of standard array types that you will want to use, that can be quickly generated.

In [ ]:
## np.ones(shape) makes an array of all ones of the desired shape
print(np.ones(1))

print()

print(np.ones((4,10)))

print()

print(np.ones((2,2,2)))

print()
print(np.ones((2,3,2)))

In [ ]:
## You code
## np.zeros(shape) is similar to np.ones, but instead of 1s
## it makes an array of 0s
## print 3 arrays of zeros, 
## one that is a single dimension of size 4


## one that is 4x5


## one that is 3x1x4


In [ ]:
## nxn identity matrix 
## np.eye(n)

## 2x2
np.eye(2)

### Built-In `numpy` Functions

`numpy` also has a number of built-in functions that provide useful mathematical operations on arrays. Let's look at some examples.

In [ ]:
y = 2*np.array([1,2,3]) - 4
y

In [ ]:
## absolute value
np.abs(y)

In [ ]:
## raising each entry to a power
np.power(y, 3)

In [ ]:
## the square root
np.sqrt(np.abs(y))

In [ ]:
## You code
## using np.exp and np.log define y to be 
## e^(x+3) + log(|x|+1)
## https://numpy.org/doc/stable/reference/generated/numpy.exp.html
## https://numpy.org/doc/stable/reference/generated/numpy.log.html
x = np.array([0,1,2,3,4])

y = 

In [ ]:
## You can sum all of the entries of an array with
## np.sum
np.sum(y)

### `numpy` for Pseudorandomness

`numpy` is useful for generating pseudorandom numbers as well. We can look at common statistics of arrays too.

The pseudorandom functionality is stored in the `random` subpackage of `numpy`. Documentation for `numpy.random` can be found here, <a href="https://numpy.org/doc/stable/reference/random/index.html">https://numpy.org/doc/stable/reference/random/index.html</a>.

In [ ]:
## random generators are stored in np.random
## a np.random.random() gives a number selected uniformly
## at random from [0,1]
## https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html
print(np.random.random())


print()

## You can get a random array of any shape as well
## just call np.random.random(tuple containing the shape)
print("A (10,2) uniform random array:\n", np.random.random((10,2)))

In [ ]:
## Another Example
## np.random.randn() is a normal(0,1) number
## a single draw
## https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html
print(np.random.randn())
print()

## an array of draws
## note the slight difference here, we don't have to put
## the 10 and 2 in a tuple to get a 10 by 2 array
## numpy is slightly inconsistent in this area so always
## check the docs to get it right
np.random.randn(10,2)

In [ ]:
## A third example
## np.random.binomial()
## an array of binomial(n,p) outcomes
## https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html
np.random.binomial(n=4, p=.3, size=(10,10))

##### Random Seeds

You may have noticed that your randomly generated numbers are different from the ones in the pre-recorded lecture (if you are watching the lecture that is!). This is expected because they are random numbers. It would be quite the coincidence if two different runs came up with the exact same random draw (for the random distributions we have looked at above).

If you want to ensure that you get the same random draw across runs you first need to set a random seed. In `numpy` this is done with `numpy.random.seed()`, <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html">https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html</a>. Let's see it in action.

In [ ]:
## Run this code chunk as many times as you'd like
## it should always give the same number

## to set a random seed you call np.random.seed(integer >= 0)
## Note that your number can be any integer so long as it is non-negative
np.random.seed(440)

np.random.randn()

In [ ]:
## You code
## make a 20 by 3 array of random normal draws
## call it X


In [ ]:
X

Now that you have a data matrix, `X`. Let's compute some summary statistics about `X`.

In [ ]:
## You can get the mean of all the entries of X with np.mean
## https://numpy.org/doc/stable/reference/generated/numpy.mean.html
print("The overall mean of X is", np.mean(X))
print()

## Adding in the argument "axis = " allows you to get
## the mean of each column
print("The column means of X are", np.mean(X, axis=0))
print()

## and the mean of each row
print("The row means of X are", np.mean(X, axis=1))
print()

## the axis argument tells numpy the axis or axes along 
## which the means are computed.
## so axis = 0 adds up the values in each row position
## and divides by the number of rows

## If you find this confusing, do not worry, I do too

In [ ]:
## You code
## np.sum also has an axis argument
## https://numpy.org/doc/stable/reference/generated/numpy.sum.html
## calculate the row sums and column sums of X
print("Row sums of X", )

print()
print()

print("Column sums of X", )




In [ ]:
## You code
## where does the max value occur in each column of X?
## https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
print("The max. values of each column of X occur at the", , "rows")


## what is the max value in each column of X?
## https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html
print("The max values in each column of X are", )


In [ ]:
## Another useful function is np.cumsum()
## https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

## randint generates a random integer between the
## first two arguments, the third argument tells numpy
## how many random draws to perform
## https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
x = np.random.randint(1,10,10)

print(x)

np.cumsum(x)

## What do you think it does?

### Linear Algebra with `numpy`

A final important use for us is `numpy` as a way to perform linear algebra calculations.

A bulk of data science algorithms use linear algebra, since we will dive into the math behind the scenes of these algorithms we will use `numpy`'s linear algebra capabilities.

##### Note: If you're not a math heavy person, that's okay! I have written the boot camp's notebooks so that you don't need to understand the math to learn how to perform the algorithms we cover. I just like to cover the mathematical aspects of these data science algorithms to explain what is going on to those boot campers (like myself) that are interested in the mathematical/statistical underpinnings of the algorithms.

In [ ]:
## We can think of a 2D array as a matrix
A = np.random.binomial(n=10,p=.4,size=(2,2))

A

In [ ]:
## A 1d array can be a row vector
x = np.array([1,2])
x.shape

In [ ]:
## or a column vector
## .reshape() will attempt to reshape your array into the given
## shape
## https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html

## When one of the shape dimensions is -1, the value is inferred from 
## the length of the array and remaining dimensions.
## so -1,1 tells numpy that you want a 2-D array with 1 column
## and it should infer the number of rows from the original shape
## of the array
## Here this reshapes x as a 2x1 column vector
x.reshape(-1, 1).shape

In [ ]:
## We can now calculate A*x
## matrix.dot() is used for matrix mult
A.dot(x.reshape(-1,1))

In [ ]:
## You code
## make a 3x1 column vector of ones, call it x
x = 

np.random.seed(576)
## Take that vector and find B*x
B = np.random.binomial(n=5, p=.6, size=(3,3))


print(B, "x", x, "=")

## code here


In [ ]:
## numpy.linalg contains a number of useful
## matrix operations, let's import a few
## note this is just for brevity in typing
from numpy.linalg import inv, eig, det

In [ ]:
## Recall our A
A

In [ ]:
## the inverse of A
## Note you may get an error here if A is not
## invertible
inv(A)

In [ ]:
## the determinant of A
det(A)

In [ ]:
## the eigenvalues and eigenvectors of A
eig(A)

## this returns a tuple of arrays
## the first entry are the eigenvalues
## the second entry are the corresponding eigenvectors

In [ ]:
## matrix.transpose() computes the transpose of the matrix
A.transpose()

In [ ]:
## You code
b = np.array([2,5]).reshape(-1,1)

## Attempt to solve Ax = b for x
## Hint remember that if A is invertible, 
## x = A^{-1} b, where A^{-1} is the inverse of A


That's it for this notebook. You have now been introduced to `numpy` and our ready to take on the practice problems. Be sure to get a fair level of comfort with `numpy`'s functionality because we will be using it a lot.

--------------------------

This notebook was written for the Erd&#337;s Institute C&#337;de Data Science Boot Camp by Matthew Osborne, Ph. D., 2023.

Any potential redistributors must seek and receive permission from Matthew Tyler Osborne, Ph.D. prior to redistribution. Redistribution of the material contained in this repository is conditional on acknowledgement of Matthew Tyler Osborne, Ph.D.'s original authorship and sponsorship of the Erdős Institute as subject to the license (see License.md)